import {
  Activity,
  ArrowLeft,
  ArrowUp,
  BarChart3,
  Bell,
  Bot,
  BookMarked,
  BookOpen,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  Clock,
  CodeXml,
  Coins,
  Compass,
  Copy,
  Crown,
  Eye,
  EyeOff,
  Globe,
  GraduationCap,
  Info,
  KeyRound,
  Lightbulb,
  LifeBuoy,
  Link,
  ListPlus,
  LogOut,
  Menu,
  MessageCircle,
  MessageCircleQuestion,
  MessagesSquare,
  Moon,
  PanelLeftClose,
  Pencil,
  PieChart,
  Plus,
  Power,
  Rocket,
  RotateCw,
  Search,
  SearchX,
  Settings,
  Settings2,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  User,
  UserPlus,
  Wand2,
  Webhook,
  X,
} from 'lucide-react';
import type { ComponentType, SVGProps } from 'react';

// Wrapper para usar icones lucide pelo nome kebab do design (ex.: "graduation-cap").
// Registry explicito (so os icones usados) para o bundle nao carregar a lib inteira.
type IconProps = SVGProps<SVGSVGElement> & { name: string; size?: number };
type LucideIcon = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string }>;

const REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'bar-chart-3': BarChart3,
  bell: Bell,
  bot: Bot,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  calendar: Calendar,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-check-big': CircleCheckBig,
  'circle-help': CircleHelp,
  clock: Clock,
  'code-xml': CodeXml,
  coins: Coins,
  compass: Compass,
  copy: Copy,
  crown: Crown,
  eye: Eye,
  'eye-off': EyeOff,
  globe: Globe,
  'graduation-cap': GraduationCap,
  info: Info,
  'key-round': KeyRound,
  lightbulb: Lightbulb,
  'life-buoy': LifeBuoy,
  link: Link,
  'list-plus': ListPlus,
  'log-out': LogOut,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-circle-question': MessageCircleQuestion,
  'messages-square': MessagesSquare,
  moon: Moon,
  'panel-left-close': PanelLeftClose,
  pencil: Pencil,
  'pie-chart': PieChart,
  plus: Plus,
  power: Power,
  rocket: Rocket,
  'rotate-cw': RotateCw,
  search: Search,
  'search-x': SearchX,
  settings: Settings,
  'settings-2': Settings2,
  shapes: Shapes,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  timer: Timer,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  user: User,
  'user-plus': UserPlus,
  'wand-2': Wand2,
  webhook: Webhook,
  x: X,
};

export function Icon({ name, strokeWidth = 1.5, ...rest }: IconProps) {
  const Cmp = REGISTRY[name] ?? Circle;
  return <Cmp strokeWidth={strokeWidth} {...rest} />;
}
